fix: Correct provider name to match the public registry
kreuzwerker/terraform-provider-docker pull request #462
Opened 2022-09-21 19:34 UTC by benley

This fixes the following error that shows up if you run the provider in debug mode:

```json
{
  "@level": "info",
  "@message": "2022/09/21 15:25:08 [ERROR] Error parsing provider name \"registry.terraform.io/kreuzwerker/terraform-provider-docker\": Invalid provider type: Provider source \"kreuzwerker/terraform-provider-docker\" has a type with the prefix \"terraform-provider-\", which isn't valid. Although that prefix is often used in the names of version control repositories for Terraform providers, provider source strings should not include it.\n\nDid you mean \"kreuzwerker/docker\"?",
  "@timestamp": "2022-09-21T15:25:08.353718-04:00"
}
```

2022-09-22 12:28 UTC, Junkern requested changes
https://registry.terraform.io/kreuzwerker/docker leads to a 404 for me, https://registry.terraform.io/providers/kreuzwerker/docker does resolve. Could you change that?

2022-09-22 16:54 UTC, benley commented
> 

Oddly enough it seems to insist on the form that leads to a 404 when loaded as a URL, because I see another error when I test with `providers/` in the provider name:

```json
{
  "@level": "info",
  "@message": "2022/09/22 12:49:55 [ERROR] Error parsing provider name \"registry.terraform.io/providers/kreuzwerker/docker\": Invalid provider source string: The \"source\" attribute must be in the format \"[hostname/][namespace/]name\"","@timestamp":"2022-09-22T12:49:55.016795-04:00"
}
```

So I believe the string used in this PR is actually correct.

2022-09-30 15:24 UTC, Junkern commented
Tests are failing due to new image sha of busybox image. WIll fix later

2022-09-30 15:25 UTC, merged

2022-09-30 18:26 UTC, benley commented
Thanks!